modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/Crendgrim/DynamicCrosshair/issues"
license = "LGPL-3.0"

[[mods]]
modId = "yaclxtest"
version = "1.0"
displayName = "YetAnotherConfigLibExtensionsTest"
authors = "Crendgrim"
description = '''
Test mod for Utility Extensions to YetAnotherConfigLib
'''
logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.yaclxtest]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yaclxtest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yaclxtest]]
modId = "yaclx"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yaclxtest]]
modId = "yet_another_config_lib"
mandatory = false
versionRange = "[3,)"
ordering = "NONE"
side = "BOTH"
